setwd("~/All ELB Work Documents/R Working Directory")
HHPower <- read.table("household_power_consumption.txt", sep=";", header = TRUE)
HHPower2 <- subset(HHPower, HHPower$Date == "1/2/2007" | HHPower$Date == "2/2/2007")
HHPower2$Date<-as.Date(as.character(HHPower2$Date),format="%d/%m/%Y")
DateTime <-as.POSIXct(paste(HHPower2$Date, as.character(HHPower2$Time), format="%Y-%m-%d %H:%M:%S"))
NewTable <- cbind(HHPower2, DateTime)
NewTable$Sub_metering_1<-as.numeric(as.character(NewTable$Sub_metering_1))
NewTable$Sub_metering_2<-as.numeric(as.character(NewTable$Sub_metering_2))
NewTable$Sub_metering_3<-as.numeric(as.character(NewTable$Sub_metering_3))
plot(NewTable$DateTime,NewTable$Sub_metering_1,type="l", xlab="",ylab="Energy sub metering")
lines(NewTable$DateTime,NewTable$Sub_metering_2, col="red")
lines(NewTable$DateTime,NewTable$Sub_metering_3, col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,col=c("black","red","blue"))
dev.copy(png,'plot3.png')
dev.off()