HHPower <- read.table("household_power_consumption.txt", sep=";", header = TRUE)
HHPower2 <- subset(HHPower, HHPower$Date == "1/2/2007" | HHPower$Date == "2/2/2007")
HHPower2$Date<-as.Date(as.character(HHPower2$Date),format="%d/%m/%Y")
DateTime <-as.POSIXct(paste(HHPower2$Date, as.character(HHPower2$Time), format="%Y-%m-%d %H:%M:%S"))
NewTable <- cbind(HHPower2, DateTime)
NewTable$Sub_metering_1<-as.numeric(as.character(NewTable$Sub_metering_1))
NewTable$Sub_metering_2<-as.numeric(as.character(NewTable$Sub_metering_2))
NewTable$Sub_metering_3<-as.numeric(as.character(NewTable$Sub_metering_3))
NewTable$Global_active_power<-as.numeric(as.character(NewTable$Global_active_power))
NewTable$Global_reactive_power<-as.numeric(as.character(NewTable$Global_reactive_power))
NewTable$Voltage<-as.numeric(as.character(NewTable$Voltage))
par(mfrow=c(2,2))
plot(NewTable$DateTime,NewTable$Global_active_power,type="l", xlab="",ylab="Global Active Power (kilowatts)")
plot(NewTable$DateTime,NewTable$Voltage,type="l", xlab="datetime",ylab="Voltage")
plot(NewTable$DateTime,NewTable$Sub_metering_1,type="l", xlab="",ylab="Energy sub metering")
lines(NewTable$DateTime,NewTable$Sub_metering_2, col="red")
lines(NewTable$DateTime,NewTable$Sub_metering_3, col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,bty='n',col=c("black","red","blue"))
plot(NewTable$DateTime,NewTable$Global_reactive_power,type="l", xlab="datetime",ylab="Global_reactive_power")
dev.copy(png,'plot4.png')
dev.off()
