HHPower <- read.table("household_power_consumption.txt", sep=";", header = TRUE)
HHPower2 <- subset(HHPower, HHPower$Date == "1/2/2007" | HHPower$Date == "2/2/2007")
HHPower2$Global_active_power<-as.numeric(as.character(HHPower2$Global_active_power))
hist(HHPower2$Global_active_power,col="red", main="Global Active Power",xlab="Global Active Power (kilowatts)")
dev.copy(png,'plot1.png')
dev.off()
